### ISSUE TITLE
Gradle Code

### ISSUE THREAD

**Issue by tellfa** [txusballesteros/fit-chart#1]
hi, tnx for this project
please add the Grdle.Build for lastet Androd Studio

**Comment by txusballesteros** [comment]
Hi @tellfa, This build.gradle of the library works fine with the **latest stable version** of Android Studio.

**Comment by tellfa** [comment]
my mean is Gardle code, for example :     compile 'com.afollestad:material-dialogs:0.7.6.0'

**Comment by txusballesteros** [comment]
Ups!! Now I can understand what do you want. I'm expecting the acceptance of the library on JCenter, when they accept and publish the repository, you can add the dependency as 'com.txusballesteros:FitChart:1.0'

**Comment by txusballesteros** [comment]
@tellfa, now you can import the library with compile 'com.txusballesteros:FitChart:1.0' command.
