### ISSUE TITLE
animationMode attribute conflicts with material-components-android attribute

### ISSUE THREAD

**Issue by MahmoudAlyuDeen** [txusballesteros/fit-chart#18]
In your attributes, you define an attribute called "animationMode", which conflicts with the attribute in the material-components-android library, preventing a successful build.

The attribute has been introduced to the material-components-android library in this commit:

https://github.com/material-components/material-components-android/blob/4dc914d737449180c6d89de5fe34c69bfe1850c4/lib/java/com/google/android/material/snackbar/res/values/attrs.xml

As you can see, it's a part of the 1.1.0-alpha01 release and it's not yet on the stable version.

**Comment by milouk** [comment]
I agree. This is an issue.

**Comment by alikamts** [comment]
Agree same issue please change it :-|

**Comment by emanuelthedude** [comment]
Same Problem here. Is there anything I can do about it?

**Comment by emanuelthedude** [comment]
Did anyone test if this workaround works? https://stackoverflow.com/questions/56255241/libraries-with-custom-attributes-conflicting

**Comment by christian-anunciado** [comment]
Same problem. How to fix this?

**Comment by emanuelthedude** [comment]
I used a different library for my use case. They also have lots of animations. I created a Pie Chart and animated kinda similar. Tell me if you need more information @SkrowRepap 
https://github.com/PhilJay/MPAndroidChart

**Comment by mgundy** [comment]
Please update.  This would be a pain to reset all my constraints with a new library.  Thank you!
